[profile.default]
solc = '0.8.23'
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 3
optimizer = false
via_ir = false

[fuzz]
runs = 10

[profile.optimized]
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
out = 'optimized-out'

[profile.intense.fuzz]
runs = 10000
